/**
 * This file is generated by `npm run gen:cmx-deps`.
 */
import type { Meta } from "@example/backend-contract";
import type * as ExampleBackendContract from "@example/backend-contract";
import * as Api from "./api.js";
import * as ExampleUiLibrary from "@example/ui-library";

type Dependency = {
  name: string;
  version: string;
  integrity: string;
  lib: Record<string, unknown>;
};

type Dependencies<Meta> = Dependency[] & { metaType: Meta };

export const dependencies = [
  {
    name: "@example/backend-contract",
    version: "workspace:*",
    integrity: "sha512-...",
    lib: Api satisfies typeof ExampleBackendContract,
  },
  {
    name: "@example/ui-library",
    version: "workspace:*",
    integrity: "sha512-...",
    lib: ExampleUiLibrary,
  },
] as unknown as Dependencies<Meta>;
