/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SlotPath = (string | number)[];

export interface CmxDocumentSchema {
  $schema: "https://cmx.xiphe.net/schemas/cmx-document.v1.schema.json";
  cmxVersion: 1;
  interface: DocumentInterface;
  content: {
    [k: string]: unknown;
  };
}
export interface DocumentInterface {
  imports: {
    [k: string]: Dependency;
  };
  exports: {
    [k: string]: DocumentExport;
  };
}
export interface Dependency {
  name: string;
  specifier: string;
  version: string;
  integrity?: string;
}
export interface DocumentExport {
  type?: TypeRef;
  slots?: SlotPath[];
}
export interface TypeRef {
  from: string;
  import?: string;
}
